AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-0dfcb1ef8550277af"
            InstanceType: "t2.micro"
            KeyName: "pacbot"
            AvailabilityZone: !Sub "${AWS::Region}e"
            Tenancy: "default"
            SubnetId: "subnet-02bfadd2405ae1300"
            EbsOptimized: false
            SecurityGroupIds: 
              - "sg-074c72bb9ceeb7f93"
            SourceDestCheck: true
            
            Tags: 
              - 
                Key: "Name"
                Value: "test-server-alpha"
            HibernationOptions: 
                Configured: false
            EnclaveOptions: 
                Enabled: false

