AWSTemplateFormatVersion: 2010-09-09
Description: Testing purposes

Resources: 
    myEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        KeyName: 
        DisableApiTermination: 
        ImageId: ami-0ff8a91507f77f867
        InstanceType: t3.micro
        Monitoring: false
        SecurityGroupIds:
          - sg-074c72bb9ceeb7f93
        UserData: !Base64 |
          #!/bin/bash -ex
          # put your script here
          yum update -y
        Tags:
          - Key: gacf-demo
            Value: test
